### ISSUE TITLE
Keep ringing after call end

### ISSUE THREAD

**Issue by duyendoan** [ringcentral/ringcentral-embeddable#636]
Hello, I've noticed that my logger is capturing this new error whenever I make an outbound call. I didn't see this the last time I checked the code, and it was around Feb 2022. The outbound call still goes through but I'm wondering if there is something going on in the backend. In addition, I'm not sure if this second issue is related to the first, but once in a while, the incoming call notification suddenly rings while the dial pad shows no call. There's no way to stop the ringing until I refresh the browser tab. No call log is recorded either. No weird error message in chrome console log tab. Again, I didn't have this issue previously. Thank you.

**Comment by embbnux** [comment]
hi @duyendoan , for keep ringing issue, the fix has been released at master build (Github Page). If you load the widget from our Github Page release, you can get that after refreshing web page. 

It will be released into stable release (CDN) after more checks at master build.

**Comment by duyendoan** [comment]
@embbnux so I'm using the widget without specifying the version. So I guess it will automatically pick up this fix right?

**Comment by embbnux** [comment]
> @embbnux so I'm using the widget without specifying the version. So I guess it will automatically pick up this fix right?

yes, it will automatically pick up this fix. BTW it is recommended to use our CDN versioned build for stable.

**Comment by duyendoan** [comment]
Hi @embbnux So one of our users still experiences this ringing issue. No call showed up on the dial pad, only the audio icon was visible on the browser tab and it kept ringing until the user turned off the tab.

**Comment by embbnux** [comment]
> > @embbnux so I'm using the widget without specifying the version. So I guess it will automatically pick up this fix right?
> 
> yes, it will automatically pick up this fix. BTW it is recommended to use our CDN versioned build for stable.

Thanks for the feedback. It is weird. Can you help to tell the user to open chrome developer tool when the issue happens again, and save logs into file (Right click to save all) at Console panel. For sending logs to us, please create a case here https://developers.ringcentral.com/support/create-case and sharing the case title in the issue.

And to make user the user have latest code: in chrome developer tool network panel, enable "disable cache", keep dev tool opened and refresh page to load new app. The browser may cache the JS files.

**Comment by duyendoan** [comment]
Hi @embbnux I submitted to the log. The case title is "Keep ringing after call end #636" (Case #16042554).

**Comment by embbnux** [comment]
@duyendoan Thanks so much for the log. I will check that.

**Comment by embbnux** [comment]
Hi @duyendoan Can you help to check if you receive same reports after you reported to us.

**Comment by embbnux** [comment]
link related https://github.com/ringcentral/ringcentral-embeddable-electron-app/issues/69

**Comment by embbnux** [comment]
Fixed with v1.8.6. Feel free to reopen this if you can still get it in new version.
